import random
kelimeler = ["beautiful","information","problem","leave","time","water","used","not","see",
              "skin", "most", "but", "lira", "play", "flower", "city", "rise", "fight", "being", "do",
              "trust", "need", "treatment", "unit", "comfortable", "cold", "there", "book", "share", "account", "body",
              'ground', 'over', 'system', 'pretty', 'withdrawal', 'technique', 'approach', 'year', 'date', 'precise', 'sister',
              "fine", "if", "whereas", "return", "give", "have", "residual", "person", "other", "period", "again", "these",
              "book", "event", "be", "you", "state", "front", "most", "look", "on", "such", "some", "start",
              "keep", "another", "none", "do", "water", "like", "state", "right", "medium", "else", "big", 
              "new", "more", "ask", "they", "turn", "both", "always", "sound", "understand", "not", "clock", "how",
              'one', 'and', 'be', 'this', 'for', 'it', 'say', 'many', 'do', 'what', 'like', 'more ', 'receive',
              'have', 'own', 'come', 'with', 'give', 'but', 'after', 'until', 'place', 'most', 'people', 'not', 'every ',
              'want', 'year', 'out', 'see', 'day', 'we', 'go', 'work', 'thing', 'call', 'that', 'know', 'hand ', 'time',
              'funny', 'child', 'two', 'look', 'work', 'in', 'big', 'absent', 'start', 'way', 'stay', 'why', 'you ',
              'subject', 'done', 'good', 'woman', 'home', 'fuck', 'boom', 'say', 'eye', 'need', 'world',
              'head', 'situation', 'side', 'pass', 'you', 'they', 'new', 'before', 'other', 'state', 'middle', 'water', 'enter', 'country',
              'eat', 'maths', 'even', 'how', 'all', 'against', 'find', 'such', 'live', 'think', 'same', 'drink', 'however', 
              'person', 'they', 'or', 'first', 'according to', 'front', 'last', 'one', 'shape', 'important', 'face', 'both', 'show ', 'make',
              'bottom', 'bring', 'use', 'because', 'side', 'now', 'man', 'his', 'other', 'now', 'on', 'sound', 'always ',
              'right', 'stand', 'girl', 'all', 'attract', 'talk', 'money', 'understand', 'mom', 'few', 'some', 'dad', 'life ',
              'just', 'small', 'more', 'information', 'moment', 'ask', 'that', 'it', 'again', 'provide', 'result', 'use', 'external', 
              'name', 'that', 'duration', 'turn', 'iron', 'sit', 'tell', 'leave', 'immediately', 'time', 'age', 'problem', 'state ',
              'have', 'row', 'write', 'percent', 'month', 'throw', 'hold', 'this', 'event', 'fall', 'hear', 'word', 'beautiful ',
              'love', 'little', 'difficult', 'Darling', 'that', 'cute', 'one', 'system', 'together', 'sister', 'who', 'uncle', 'young ',
              'door', 'book', 'on', 'here', 'night', 'area', 'science', 'here', 'wait', 'long', 'no', 'today', 'period', 
              'friend', 'product', 'family', 'three', 'read', 'man', 'everyone', 'power', 'maybe', 'real', 'full', 'related', 'relationship ',
              'environment', 'old', 'search', 'life', 'people', 'near', 'street', 'squire', 'history', 'property', 'section', 'private', 'reason',
              'nobody', 'sex', 'if', 'need', 'especially', 'meaning', 'high', 'bank', 'once', 'foot', 'move', 'back', 'society',
              'tool', 'item', 'type', 'decision', 'see', 'air', 'number', 'different', 'group', 'room', 'form', 'form', 'news',
              'allah', 'also', 'incoming', 'few', 'question', 'back', 'win', 'post', 'school', 'open', 'learn', 'drive',
              'language', 'company', 'source', 'finish', 'program', 'continue', 'move', 'color', 'unfold', 'right', 'believe',
              'study', 'angle', 'piece', 'newspaper', 'compose', 'of course', 'value', 'know', 'structure', 'doctor', 'income',
              'task', 'purpose', 'region', 'movie', 'to', 'customer', 'already', 'phone', 'education', 'sea', 'second','get up', 'even', 'impact', 'evolve', 'pass', 'body', 'thought', 'million', 'play', 'change', 'base',
              'create', 'reach', 'think', 'pass', 'culture', 'construct', 'but', 'to this', 'painting', 'light', 'drinking',
              'lady', 'service', 'need', 'point', 'direction', 'yes', 'game', 'increase', 'reuse', 'process', 'short', 'easy',
              'which', 'rate', 'actually', 'accept', 'there', 'attention', 'far', 'computer', 'future', 'appear',
              'eg', 'son', 'listening', 'appropriate', 'lira', 'production', 'minute', 'forget', 'walk', 'so', 'bad',
              'car', 'mouth', 'feeling', 'apply', 'still', 'example', 'many', 'watch', 'degree', 'possible', 'such',
              'wall', 'ten', 'art', 'main', 'illness', 'student', 'television', 'method', 'table', 'die', 'team', 'top',
              'head', 'music', 'circle', 'energy', 'university', 'sport', 'kind', 'soul', 'despite', 'part', 'death',
              'constant', 'health', 'various', 'from this', 'feel', 'whereas', 'morning', 'internet', 'technical', 'out',
              'center', 'environment', 'instead', 'level', 'village', 'management', 'down', 'answer', 'lay', 'land','', 'evening',
              'research', 'take away', 'participate', 'otherwise', 'establish', 'pay', 'as if', 'blood', 'sick', 'city', 'descend',
              'present', 'known', 'week', 'traffic', 'account', 'car', 'alien', 'behavior', 'kitchen', 'city', 'sometimes',
              'certain', 'separate', 'price', 'about', 'remove', 'arm', 'alone', 'prepare', 'glass', 'finally', 'slow',
              'necessary', 'importance', 'husband', 'false', 'asset', 'art', 'interest', 'you', 'sale', 'in', 'natural', 'own',
              'economic', 'pain', 'no', 'protect', 'floor', 'economy', 'general', 'specify', 'photo', 'animal', 'war',
              'goods', 'hair', 'lose', 'remainder', 'change', 'four', 'really', 'page', 'technology', 'institution', 'five',
              'sector', 'broad', 'paper', 'fragrance', 'right', 'hot', 'century', 'street', 'market', 'sustain', 'use', 'class',
              'love', 'born', 'heavy', 'again', 'sun', 'cigarette', 'tree', 'word', 'building', 'wife', 'run away', 'party', 'bed ',
              'author', 'ear', 'teacher', 'reason', 'left', 'well', 'oil', 'because of', 'understand', 'arrive', 'laugh', 'rule',
              'sell', 'poetry', 'send', 'success', 'firm', 'government', 'heart', 'cut', 'project', 'must', 'speed', 'corner',
              'hit', 'model', 'fish', 'market', 'view', 'here', 'prepare', 'amount', 'first', 'square', 'measure',
              'choose', 'applied', 'garden', 'love', 'bread', 'along', 'run', 'hail', 'establishment', 'saye', 'fear',
              'help', 'encounter', 'stuff', 'nice', 'dog', 'famous', 'grow', 'walk around', 'quite', 'moreover',
              'tamil', 'white', 'want', 'beyond', 'trying', 'brother', 'withdrawal', 'where', 'stealing', 'permission', 'fear',
              'occupation', 'police', 'only', 'explain', 'idea', 'quick', 'window', 'there', 'stone', 'fire', 'difference',
              'enough', 'most', 'some', 'condition', 'neighborhood', 'must', 'grain', 'produce', 'door', 'dear', 'thin',
              'deer', 'common', 'type', 'image', 'since', 'lesson', 'chairman', 'counter', 'came', 'number', 'times',
              'to be', 'west', 'realize', 'any', 'cinema', 'different', 'target', 'sleep', 'friend', 'burn',
              'understanding', 'master', 'press', 'edge', 'control', 'flip', 'religion', 'strong', 'yet', 'plan', 'brain',
              'electric', 'wife', 'on', 'meat', 'provided', 'sung', 'line', 'fly', 'member', 'skin', 'spirit',
              'dear', 'approach', 'process', 'gaze', 'science', 'forward', 'expression', 'body', 'remember', 'accident',
              'english', 'mountain', 'close', 'step', 'serious', 'solution', 'impress', 'municipality', 'development', 'election', 'cry', 'connected', 'concept', 'increase', 'activity', 'harm', 'deep', 'salon', 'brust', 'Vikram',
              'watch', 'suddenly', 'contain', 'toys', 'collection', 'ten', 'fore', 'responsibility', 'rolex',
              'letter', 'cold', 'live', 'idikeylem', 'machine', 'utilise', 'old', 'blank', 'wonder', 'match', 'manager',
              'brought', 'meter', 'kept', 'quality', 'plant', 'change', 'medicine', 'credit', 'law', 'successful',
              'one', 'opportunity', 'punishment', 'everything', 'inspect', 'ball', 'expert', 'fill up', 'channel', 'space', 'fit',
              'yearly', 'therefore', 'wonderful', 'belonging', 'finger', 'count', 'to throw', 'determine', 'normal', 'hele',
              'principle', 'red', 'role', 'song', 'staff', 'ready', 'like', 'something', 'teacher', 'boy', 'daily', 'politics',
              'crime', 'why', 'stage', 'stuck', 'custom', 'seat', 'save', 'artist', 'prefer', 'reached', 'stage',
              'add', 'forest', 'separate', 'order', 'interest', 'usually', 'always', 'story', 'cell', 'there', 'novel',
              'tax', 'burn', 'brother', 'press', 'support', 'wear', 'mistake', 'limit', 'unity', 'work', 'meet',
              'half', 'enough', 'individual', 'dark', 'bus', 'industry', 'baby', 'citizen', 'minister', 'time', 'nation',
              'ad', 'rise', 'size', 'magazine', 'inflation', 'social', 'someone', 'past', 'hospital', 'being',
              'meeting', 'journalist', 'inside', 'faith', 'quality', 'over', 'finish', 'take place', 'introduction', 'comfortable',
              'total', 'together', 'shop', 'secret', 'similar', 'skin', 'transform', 'fight', 'problem', 'service', 'cure',
              'green', 'ministry', 'pressure', 'reaction', 'sentence', 'wish', 'freedom', 'again', 'identity', 'issue', 'third',
              'determine', 'evaluate', 'interesting', 'drive', 'milk', 'catch', 'item', 'international', 'candidate',
              'weight', 'billion', 'healthy', 'distress', 'god', 'attitude', 'social', 'publication', 'careful', 'extremely',
              'gather', 'invest', 'light', 'mix', 'danger', 'time', 'circle', 'opportunity', 'process', 'mix',
              'contribution', 'story', 'totally', 'plane', 'response', 'nature', 'marry', 'nose', 'interest', 'course', 'worker', 'business',
              'briefly', 'store', 'media', 'because of', 'increase', 'take out', 'public', 'insurance', 'summer', 'heart', 'document',
              'effort', 'everyday', 'express', 'risk', 'talk', 'word', 'democracy', 'salt', 'mosque', 'age', 'low',
              'around', 'quickly', 'opportunity', 'organ', 'dad', 'other', 'year', 'mom', 'zues', 'fruit', 'posiden',
              'sweet', 'leg', 'change', 'law', 'wind', 'republic', 'improve', 'style', 'seven', 'decrease',
              'connect', 'cellphone', 'communication', 'manager', 'hotel', 'run', 'enjoy', 'ride', 'security', 'law',
              'make', 'modern', 'read', 'gun', 'demand', 'star', 'intense', 'soldier', 'simple', 'element', 'gas',
              'application', 'produce', 'declaration', 'food', 'yesterday', 'see', 'about', 'shopping', 'consciousness', 'framework',
              'need', 'available', 'consumer', 'extend', 'to', 'at', 'connect', 'eg', 'almost', 'site',
              'help', 'sister', 'flower', 'all', 'respect', 'pay', 'talent', 'weight', 'share', 'hard', 'besides',
              'tea', 'goes', 'certain', 'rich', 'never', 'word', 'organization', 'trade', 'find', 'neck', 'device',
              'balance', 'sticker', 'back', 'sond', 'coffee', 'muscle', 'assembly', 'other', 'to deal with', 'address', 'tech',
              'pasha', 'warmth', 'ok', 'trust', 'brand', 'leaf', 'benefit', 'spread', 'flowing', 'drawing', 'thinking',
              'heart', 'dream', 'progress', 'wine', 'above', 'gold', 'arrange', 'buy', 'present', 'clean',
              'vitamin', 'supplement', 'late', 'acting', 'egg', 'excessive', 'action', 'want', 'cut', 'crisis', 'unit',
              'shut down'
              ]
def kelime_sec():
   return random.choice(kelimeler)


